version: "3"

services:
  mediboard:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mediboard_db
    ports:
      - "80:80"
    networks:
      - mediboard_net

    volumes:
      - mediboard_app_data:/var/www/html/mediboard/
      # Ce volume va persister les fichiers de configuration de Mediboard.
      - mediboard_config:/var/www/html/mediboard/includes/

  mediboard_db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mediboard_db
      MYSQL_USER: mediuser
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    networks:
      - mediboard_net
    volumes:
      - db_data:/var/lib/mysql

networks:
  mediboard_net:

volumes:
  mediboard_app_data:
  mediboard_config:
  db_data: